### ISSUE TITLE
Confusion in error syntax: "errors" vs. "error"

### ISSUE THREAD

**Issue by lwindolf** [theoldreader/api#28]
The "Error" section says all JSON errors have format:

    {
        errors: [
            "Temporary unavailable, please try later"
        ]
    }

and the subscription callback section says

     [...]"error":"Feed was not added.[...]

I guess on batch actions there is an "errors" array and on single actions there is just the field.

**Comment by krasnoukhov** [comment]
Hello, thanks for noticing! You are right, `Adding subscription` method returns single `error` since it mimics old Google Reader behaviour. I've fixed the doc.
