### ISSUE TITLE
Follow / unfollow friends error

### ISSUE THREAD

**Issue by Sergio-Muriel** [theoldreader/api#33]
The follow and unfollow don't look to be working (i am missing something?):

Followed user:
 - user/xxxxxxxxxxxxxxxxx/state/com.google/broadcast 

Tried to POST on https://theoldreader.com/reader/api/0/friends/edit with:
- action: removefollowing
- u: user/xxxxxxxxxxxxxxxxx/state/com.google/broadcast

or

- action: removefollowing
- u: xxxxxxxxxxxxxxxxxx

Got always the same response:
<errors type="array">
  <error>Not found</error>
</errors>

I have got the same probleme with the addfollowing method.

**Comment by jfiorato** [comment]
Hi,

This is just a documentation typo. The endpoint should be "
https://theoldreader.com/reader/api/0/friend/edit" (not "friends").

I've updated the documentation.

Sorry for that.
The Old Reader Team
