### ISSUE TITLE
Error getting comments

### ISSUE THREAD

**Issue by Sergio-Muriel** [theoldreader/api#36]
Adding comments looks to work fine as the result is "OK", but retrieveing the feed content still get an empty array for  comments.

Added comment with:
- url: 'https://theoldreader.com/reader/api/0/comment/edit'
- post data: 
   * comment: 'Por fin!'
   * i: 'tag:google.com,2005:reader/item/54eda62e315adec5b5007e2c'

Result is: OK

Then fetch feed content with: https://theoldreader.com/reader/api/0/stream/items/contents?output=json&i=54eda62e315adec5b5007e2c
Result is: empty array for comments

**Comment by krasnoukhov** [comment]
Are you sure you're adding a comment on a shared item? We always respond with `OK` to mimic old GR behavior, but adding on regular item just does nothing.

**Comment by Sergio-Muriel** [comment]
Ups sorry, misunderstood the functionality then. Closed.
