### ISSUE TITLE
Unable to unsubscribe from a feed

### ISSUE THREAD

**Issue by PomepuyN** [theoldreader/api#40]
When trying to unsubscribe from a feed, I get the "OK" result, but nothing is done on the server.

Example:

```
POST https://theoldreader.com/reader/api/0/subscription/edit?ac=unsubscribe&s=feed%2F556c2d01c70bc2989e0000d8
```

**Comment by Sergio-Muriel** [comment]
It is working fine here.
Note that the params must be passed via POST parameters, not GET.

**Comment by PomepuyN** [comment]
That was indeed the issue. Thanks for the help.
