### ISSUE TITLE
Cannot create new folder

### ISSUE THREAD

**Issue by JeremyJeanson** [theoldreader/api#42]
Hi,

I haven't found a way to use this API to create new folders. I was hoping to find something like a POST to "reader/api/0/add-tag" or something else.

Did i missed something?

**Comment by jfiorato** [comment]
It's a little convoluted, but you can only create a new folder when moving a feed to it. See https://github.com/theoldreader/api#updating-subscription

Reason it is this way is that folders with no subscriptions in them are automatically deleted.
